version: "3.8"
services:
  #react.js ( web )
  web:
    build: ./frontend
    #Communique avec l'api 
    depends_on:
      - api
    ports:
      - "8000:80"
    networks:
      - network-backend
  apirest:
    build: ./backend
    #Communique avec mango
    depends_on:
      - mongodb
    ports:
      - "8080:80"
    networks: 
     - network-backend
  
  mongoDB:
    image: mongo
    restart: always
    volumes: 
      - mongodb:/data/mangodb
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: Omar
      MONGODB_INITDB_ROOT_PASSWORD: password 
      
      ports:
      - "8093:80"
    
    networks: 
     - network-backend

 networks:
  network-backend

volumes: 
  mongodb:
